add sponsors links
osm-fr/sotmfr-website pull request #127
Opened 2023-05-15 16:52 UTC by tykayn

2023-05-18 05:21 UTC, vinber commented
Est ce que c'est bon ? Peut-on déployer ?

2023-05-18 09:11 UTC, tykayn commented
![Screenshot 2023-05-18 at 11-06-50 State of the Map France 2023 - Mentions légales](https://github.com/osm-fr/sotmfr-website/assets/3931245/76bcc9cc-dda1-4200-b348-52a12dfc9d5f)

ça ressemble à ceci

2023-05-19 11:38 UTC, JackNUMBER commented on 2023/images/soutiens/logo_code_lutin.svg
Peut-on redimentionner les images à la taille à laquelle elles seront affichées sur le site ? C'est une bonne pratique pour les usagers avec un débit limité.

2023-05-19 11:38 UTC, JackNUMBER commented on 2023/sponsors.html
> +<!--                            <img class="logo p-1" src="images/soutiens/logo_tomtom.png" alt="logo tomtom" width="200">-->
On pourrait enlever ce commentaire ?

2023-05-19 13:58 UTC, marcelezd commented on 2023/images/soutiens/logo_code_lutin.svg
pour un svg, ça ne changera rien sauf si on simplifie l'image pour gagner quelques octets mais je suis d'avis de trouver une version vectorielle des logos qui sont encore en png.

2023-05-19 14:01 UTC, JackNUMBER commented on 2023/images/soutiens/logo_code_lutin.svg
Oui en effet pour les fichiers SVG ça n'a pas d'incidence. J'ai mi le commentaire sur une image au hasard.

2023-05-19 14:10 UTC, marcelezd requested changes

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_latitude_cartagene.png
version svg : https://latitude-cartagene.com/wp-content/uploads/2019/12/LC_LOGO_NOIR_RVB_145x40.svg

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_universite_de_nantes.svg
pas utilisé

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_open_data_soft.png
version svg : https://www.opendatasoft.com/wp-content/uploads/2022/12/logo-opendatasoft.svg

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_michelin.png
version svg : https://www.michelin.com/wp-content/themes/michelin/public/img/michelin-logo.svg

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_sogefi.png
version svg : https://www.sogefi-sig.com/wp-content/uploads/2022/04/logo_sogefi_horiz_rvb.svg

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_wemap.png
version svg : https://getwemap.com/images/logo-wemap.svg

2023-05-19 14:10 UTC, marcelezd commented on 2023/images/soutiens/logo_2i2L.png
la version svg sur leur site n'est présente que sur le footer, il faut la recolorier

2023-05-19 14:13 UTC, marcelezd commented
la branche n'est pas à jour par rapport à l'image, par exemple, le logo wemap est sur l'image mais pas dans le code

2023-05-19 14:17 UTC, marcelezd commented on 2023/images/soutiens/logo_2i2L.png
![2i2l](https://github.com/osm-fr/sotmfr-website/assets/59266536/fb86e8bf-3348-464f-b32b-5489ac0d9c6a)

2023-05-22 07:16 UTC, vinber commented
bonjour,
je ne sais pas ce qu'il faut faire pour que cela soit publié ?

nous avons quelques versements qui ont eu lieu, cela serait chouette de montrer cela sur le site :) 

@tykayn @JackNUMBER @marcelezd @ThomasG77  ?

2023-05-22 20:01 UTC, JackNUMBER commented
@vinber Il faut que les commentaires de la PR soit traités.

2023-05-22 21:39 UTC, ThomasG77 commented
Hello,
Adressé via https://github.com/osm-fr/sotmfr-website/commits/tykayn-111-sponsors où j'ai ajouté les SVG et changé les références dans `sponsors.html`, mis à jour `main.css`. Il suffit de cherry-pick mon commit pour l'appliquer à la PR actuelle.

Mon problème est que la capture d'écran de la PR mentionne Latitude Carthagène par exemple mais je ne trouve pas ces mêmes refs dans `sponsors.html`.

2023-05-22 21:41 UTC, ThomasG77 commented on 2023/sponsors.html
> +        </style>
Done mais pas cherché à adresser le problème via Bootstrap (voir dernier commentaire pour le commit associé)

2023-05-22 21:41 UTC, ThomasG77 commented on 2023/images/soutiens/logo_jawg.png
Supprimée

2023-05-22 21:42 UTC, ThomasG77 commented on 2023/images/soutiens/logo_universite_de_nantes.svg
Supprimée

2023-05-22 21:42 UTC, ThomasG77 commented on 2023/images/soutiens/logo_open_data_soft.png
Done  (voir dernier commentaire pour le commit associé)

2023-05-22 21:42 UTC, ThomasG77 commented on 2023/images/soutiens/logo_michelin.png
Done (voir dernier commentaire pour le commit associé)

2023-05-22 21:42 UTC, ThomasG77 commented on 2023/images/soutiens/logo_wemap.png
Done

2023-05-22 21:43 UTC, ThomasG77 commented on 2023/images/soutiens/logo_2i2L.png
Done (voir dernier commentaire pour le commit associé)

2023-05-23 06:01 UTC, vinber commented
latitude carthagene fait bien partie des sponsors, niveau 2 / logo ici https://nextcloud.openstreetmap.fr/index.php/s/KKBXGdNxFz6Zxip

url website https://latitude-cartagene.com/

2023-05-23 08:29 UTC, ThomasG77 commented
Voir la capture d'écran de la page sponsors de lAPR qui montre le décalage sur le contenu du fichier sponsors.html actuel et la capture d'écran https://github.com/osm-fr/sotmfr-website/pull/127#issuecomment-1552767576
@tykayn Tu sais pourquoi on a ce décalage?

2023-05-23 09:53 UTC, vinber commented
> Technique ou lié à l'avancement des conventions de sponsoring?

technique, c'est moi qui gère les conventions de sponsoring et je confirme que LC doit y être

il manque également wemap ?

Donc je reprends
- les logos sont ici dans des dossiers Niveau1, 2, et 3 (https://nextcloud.openstreetmap.fr/index.php/s/SwwYtgNzgBR6me8=
- il n'y a pas de niveau 1 cette année
- niveau 2 (latitude cartagene, makina corpus, meta, opendatasoft, tomtom, wemap
- niveau 3 (2i2l, cartocite, geovelo, jawgmaps, Kprod, Magelium, Veremes)

2023-05-23 11:24 UTC, ThomasG77 commented
Le rendu après changements en GIF (PS: le logo Meta a l'URL qui pointe sur [Mappilary](https://www.mapillary.com/))
Les logos niveaux 2 = 300px de large et pour les niveaux 3, 200px

![capture-rendu-actuel-sponsors](https://github.com/osm-fr/sotmfr-website/assets/642120/daa1cd4a-a041-4c65-8ae2-faddd963e177)

Attente retours et ensuite merge si OK

2023-05-23 13:17 UTC, closed without merging